### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by ABSanthosh** [mszoek/hydrogen#3]
Hey!

I came across this project while exploring GitHub and I think this is awesome!

Would love to learn more about OS but don't know where to start. If you can share some resources that helped you learn for this project, Please share them too so I can learn too!

Thanks in advance!

**Comment by mszoek** [comment]
Hi! That's very cool... I had a lot of fun doing this. OSDev is a great starting point and I found it very useful - https://wiki.osdev.org/Main_Page

**Comment by ABSanthosh** [comment]
Will definitely check it out. Thanks!
